version: '3'

services:
  hexo:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./source:/app/source
      - ./themes:/app/themes
      - ./_config.yml:/app/_config.yml
    command: pnpm run server