version: '3'

services:
  # 本地开发：启动 hexo server
  hexo:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./source:/app/source
      - ./themes:/app/themes
      - ./_config.yml:/app/_config.yml
    command: pnpm run server

  # CI 构建服务：只构建静态文件
  hexo-builder:
    build: .
    environment:
      - BUILD_ONLY=true
    volumes:
      - ./public:/app/public  # 导出构建结果
    command: /bin/true  # 什么都不做，避免执行 CMD 中的 server
